export let catDict = {
    "Abyssinian": "abys",
    "American Bobtail": "abob",
    "American Curl": "acur",
    "American Shorthair": "asho",
    "American Wirehair": "awir",
    "Bengal": "beng",
    "Birman": "birm",
    "Bombay": "bomb",
    "British Shorthair": "bsho",
    "Burmese": "bure",
    "Burmilla": "buri",
    "Canadian Hairless": "sphy",
    "Chartreux": "char",
    "Chausie": "chau",
    "Chinchilla": "pers",
    "Cornish Rex": "crex",
    "Cymric": "cymr",
    "Devon Rex": "drex",
    "Domestic Long Hair": "bslo",
    "Domestic Medium Hair": "bslo",
    "Domestic Short Hair": "bsho",
    "Egyptian Mau": "emau",
    "Exotic Shorthair": "esho",
    "Havana": "hbro",
    "Himalayan": "hima",
    "Japanese Bobtail": "jbob",
    "Javanese": "java",
    "Korat": "kora",
    "LaPerm": "lape",
    "Maine Coon": "mcoo",
    "Manx": "manx",
    "Munchkin": "munc",
    "Nebelung": "nebe",
    "Norwegian Forest Cat": "norw",
    "Ocicat": "ocic",
    "Oriental Long Hair": "orie",
    "Oriental Short Hair": "orie",
    "Oriental Tabby": "orie",
    "Persian": "pers",
    "Pixiebob": "pixi",
    "Ragamuffin": "raga",
    "Ragdoll": "ragd",
    "Russian Blue": "rblu",
    "Scottish Fold": "sfol",
    "Selkirk Rex": "srex",
    "Siamese": "siam",
    "Siberian": "sibe",
    "Singapura": "sing",
    "Snowshoe": "snow",
    "Somali": "soma",
    "Sphynx / Hairless Cat": "sphy",
    "Tonkinese": "tonk",
    "Toyger": "toyg",
    "Turkish Angora": "tang",
    "Turkish Van": "tvan",
    "York Chocolate": "ycho"
}

export let dogDict = {
    "Affenpinscher": 1,
    "Afghan Hound": 2,
    "Airedale Terrier": 4,
    "Akbash": 5,
    "Akita": 6,
    "Alaskan Malamute": 9,
    "American Bulldog": 10,
    "American Bully": 11,
    "American Eskimo Dog": 12,
    "American Foxhound": 14,
    "American Hairless Terrier": 15,
    "American Staffordshire Terrier": 16,
    "American Water Spaniel": 17,
    "Anatolian Shepherd": 18,
    "Appenzell Mountain Dog": 19,
    "Australian Cattle Dog / Blue Heeler": 21,
    "Australian Kelpie": 22,
    "Australian Shepherd": 23,
    "Australian Terrier": 24,
    "Basenji": 28,
    "Basset Hound": 30,
    "Beagle": 31,
    "Bearded Collie": 32,
    "Beauceron": 33,
    "Bedlington Terrier": 34,
    "Belgian Shepherd / Malinois": 36,
    "Belgian Shepherd / Tervuren": 38,
    "Bernese Mountain Dog": 41,
    "Bichon Frise": 42,
    "Black and Tan Coonhound": 43,
    "Bloodhound": 45,
    "Bluetick Coonhound": 47,
    "Boerboel": 48,
    "Border Collie": 50,
    "Border Terrier": 53,
    "Boston Terrier": 53,
    "Bouvier des Flandres": 54,
    "Boxer": 55,
    "Boykin Spaniel": 56,
    "Briard": 58,
    "Brittany Spaniel": 59,
    "Bull Terrier": 61,
    "Bullmastiff": 64,
    "Cairn Terrier": 65,
    "Cane Corso": 67,
    "Cardigan Welsh Corgi": 68,
    "Catahoula Leopard Dog": 69,
    "Caucasian Sheepdog / Caucasian Ovtcharka": 70,
    "Cavalier King Charles Spaniel": 71,
    "Chesapeake Bay Retriever": 76,
    "Chinese Crested Dog": 78,
    "Chinook": 80,
    "Chow Chow": 81,
    "Clumber Spaniel": 84,
    "Cocker Spaniel": 86,
    "Coton de Tulear": 89,
    "Dalmatian": 92,
    "Doberman Pinscher": 94,
    "Dogo Argentino": 95,
    "Dutch Shepherd": 98,
    "English Setter": 101,
    "English Shepherd": 102,
    "English Springer Spaniel": 103,
    "English Toy Spaniel": 104,
    "Field Spaniel": 108,
    "Finnish Lapphund": 110,
    "Finnish Spitz": 111,
    "French Bulldog": 113,
    "German Pinscher": 114,
    "German Shepherd Dog": 115,
    "German Shorthaired Pointer": 116,
    "Giant Schnauzer": 119,
    "Glen of Imaal Terrier": 120,
    "Golden Retriever": 121,
    "Gordon Setter": 123,
    "Great Dane": 124,
    "Great Pyrenees": 125,
    "Greyhound": 127,
    "Harrier": 129,
    "Havanese": 130,
    "Irish Setter": 134,
    "Irish Terrier": 135,
    "Irish Wolfhound": 137,
    "Italian Greyhound": 138,
    "Japanese Chin": 140,
    "Keeshond": 142,
    "Komondor": 144,
    "Kuvasz": 147,
    "Labrador Retriever": 149,
    "Lancashire Heeler": 153,
    "Leonberger": 155,
    "Lhasa Apso": 156,
    "Maltese": 161,
    "Miniature Pinscher": 167,
    "Miniature Schnauzer": 168,
    "Newfoundland Dog": 171,
    "Norfolk Terrier": 172,
    "Norwich Terrier": 176,
    "Nova Scotia Duck Tolling Retriever": 177,
    "Old English Sheepdog": 178,
    "Papillon": 181,
    "Pekingese": 183,
    "Pembroke Welsh Corgi": 184,
    "Pharaoh Hound": 188,
    "Plott Hound": 189,
    "Pomeranian": 193,
    "Poodle": 197,
    "Pug": 201,
    "Puli": 204,
    "Pumi": 205,
    "Rat Terrier": 207,
    "Redbone Coonhound": 208,
    "Rhodesian Ridgeback": 209,
    "Rottweiler": 210,
    "Saint Bernard": 212,
    "Saluki": 213,
    "Samoyed": 214,
    "Schipperke": 216,
    "Scottish Deerhound": 218,
    "Scottish Terrier": 219,
    "Shetland Sheepdog / Sheltie": 221,
    "Shiba Inu": 222,
    "Shih Tzu": 223,
    "Siberian Husky": 225,
    "Silky Terrier": 228,
    "Smooth Fox Terrier": 232,
    "Spanish Water Dog": 235,
    "Spinone Italiano": 236,
    "Staffordshire Bull Terrier": 238,
    "Standard Schnauzer": 239,
    "Swedish Vallhund": 242,
    "Thai Ridgeback": 243,
    "Tibetan Mastiff": 244,
    "Tibetan Spaniel": 245,
    "Tibetan Terrier": 246,
    "Toy Fox Terrier": 248,
    "Treeing Walker Coonhound": 250,
    "Vizsla": 251,
    "Weimaraner": 253,
    "Welsh Springer Spaniel": 254,
    "West Highland White Terrier / Westie": 256,
    "Whippet": 257,
    "White German Shepherd": 258,
    "Wire Fox Terrier": 259,
    "Wirehaired Pointing Griffon": 261,
    "Xoloitzcuintli / Mexican Hairless": 262,
    "Yorkshire Terrier": 264
}